name: BuildFlutterWindowsApp

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: CheckoutCode
        uses: actions/checkout@v3
      
      - name: SetupFlutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      
      - name: SetupPython
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: InstallPythonDependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyvisa pyvisa-py pandas openpyxl
      
      - name: GetFlutterDependencies
        run: flutter pub get
      
      - name: FlutterDoctor
        run: flutter doctor -v
      
      - name: BuildWindowsApp
        run: flutter build windows --release
      
      - name: PackageWindowsApp
        run: |
          cd build/windows/runner/Release
          7z a -tzip ../../../../jn_production_line_windows_${{ github.sha }}.zip *
      
      - name: UploadArtifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-release
          path: jn_production_line_windows_*.zip
          retention-days: 30
      
      - name: CreateRelease
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: jn_production_line_windows_*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
