version: 1.0

name: build-flutter-windows
displayName: BuildFlutterWindowsApplication

trigger:
  push:
    - master
    - main

variables:
  FLUTTER_VERSION: '3.24.0'

stages:
  - stage: build
    displayName: BuildStage
    jobs:
      - job: build-windows
        displayName: BuildWindowsApplication
        pool:
          name: Default
          demands:
            - Agent.OS -equals Windows_NT
        steps:
          - step: checkout@1
            displayName: CheckoutCode
            with:
              repository: self
              clean: true
          
          - step: script@1
            displayName: InstallFlutterSDK
            inputs:
              script: |
                curl -o flutter_windows.zip https://storage.flutter-io.cn/flutter_infra_release/releases/stable/windows/flutter_windows_3.24.0-stable.zip
                tar -xf flutter_windows.zip
                set PATH=%CD%\flutter\bin;%PATH%
                flutter --version
                flutter doctor
          
          - step: script@1
            displayName: InstallPythonDependencies
            inputs:
              script: |
                python --version
                python -m pip install --upgrade pip
                pip install pyvisa pyvisa-py pandas openpyxl
          
          - step: script@1
            displayName: GetFlutterDependencies
            inputs:
              script: |
                set PATH=%CD%\flutter\bin;%PATH%
                flutter pub get
          
          - step: script@1
            displayName: BuildWindowsApplication
            inputs:
              script: |
                set PATH=%CD%\flutter\bin;%PATH%
                flutter build windows --release
          
          - step: script@1
            displayName: PackageBuildArtifacts
            inputs:
              script: |
                move build\windows\x64\runner\Release\jn_production_line.exe ..\..\..\..\
          
          - step: publish@1
            displayName: PublishBuildArtifacts
            inputs:
              artifacts: jn_production_line_windows.exe   
              artifactName: windows-release
